name: Synpress tests

on:
  push:
    branches: [cent-app/synpress-testing-setup, 'main']

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Synpress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: centrifuge-app
          install-command: yarn
          command: yarn e2e:run:ci
          browser: chrome
          config-file: synpress.config.js
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
