name: Synpress tests

on:
  push:
    branches: [cent-app/synpress-testing-setup, 'main']

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #@v3.6.0
        with:
          node-version: '18'
          cache: yarn
      - name: Synpress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: centrifuge-app
          install-command: yarn
          build: |
            yarn
            yarn build:fabric 
            yarn build:centjs 
            yarn build:centReact
            cat .env-config/.env.development
            yarn build:app --mode development
          start: yarn preview
          wait-on: 'http://localhost:4173'
          command: yarn e2e:run:ci
          browser: chrome
          config-file: synpress.config.ts
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
