name: Synpress tests

on:
  push:
    branches: [cent-app/synpress-testing-setup, 'main']

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0
      - name: Synpress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: centrifuge-app
          install-command: yarn
          command: |
            env
            yarn e2e:run:ci
          browser: chrome
          config-file: synpress.config.ts
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PRIVATE_KEY: ${{ secrets.CYPRESS_PRIVATE_KEY }}
          PRIVATE_KEY: ${{ secrets.CYPRESS_PRIVATE_KEY }}
          CYPRESS_BASE_URL: https://app-dev.k-f.dev
          DISPLAY: :0.0
